# Generated by Django 2.2.7 on 2019-11-24 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visiting_host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='myapp.Host'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 17, 44, 56, 439742), verbose_name='time arrived'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkout_time',
            field=models.TimeField(verbose_name='time leaving'),
        ),
    ]
