# Generated by Django 2.2.7 on 2019-11-24 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191124_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 19, 5, 50, 807966), verbose_name='time arrived'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkout_time',
            field=models.TimeField(blank=True, verbose_name='time leaving'),
        ),
    ]
