# Generated by Django 2.2.7 on 2019-11-24 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191124_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 19, 9, 59, 258499), verbose_name='time arrived'),
        ),
    ]
