# Generated by Django 2.2.7 on 2019-11-25 17:32

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191124_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 17, 32, 7, 536812), verbose_name='time arrived'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
