# Generated by Django 2.2.7 on 2019-11-25 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191125_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 17, 35, 39, 161177), verbose_name='time arrived'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
