# Generated by Django 2.2.7 on 2019-11-25 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191125_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 18, 10, 17, 944960), verbose_name='time arrived'),
        ),
    ]
